inherit_from: ./.rubocop_todo.yml

AllCops:
  Exclude:
    - 'performance/shopify/*'
    - 'pkg/**'

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/FormatString:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/DeprecatedHashMethods:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Performance/Count:
  Enabled: false

Style/ConstantName:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/WordArray:
  Enabled: false
