inherit_from: ./.rubocop_todo.yml

AllCops:
  Exclude:
    - 'performance/shopify/*'
    - 'pkg/**'

Metrics/BlockNesting:
  Max: 3

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/LiteralInCondition:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Style/FormatString:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Performance/Count:
  Enabled: false

Style/ConstantName:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/WordArray:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'example/server/liquid_servlet.rb'
