inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_from:
  - .rubocop_todo.yml

require: rubocop-performance

Performance:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  Exclude:
    - 'vendor/bundle/**/*'

Naming/MethodName:
  Exclude:
    - 'example/server/liquid_servlet.rb'

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line
