inherit_from:
  - 'https://shopify.github.io/ruby-style-guide/rubocop.yml'
  - .rubocop_todo.yml

require: rubocop-performance

Performance:
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'

Naming/MethodName:
  Exclude:
    - 'example/server/liquid_servlet.rb'
